### ISSUE TITLE
error: templates must have C++ linkage and more.. 

### ISSUE THREAD

**Issue by sovanna** [nidium/Nidium#27]
Bellow what I have..

```bash
clang++ -o Compression.o -c  -I/nidium/Nidium/third-party/.default/mozilla-central/js/src/obj/dist/system_wrappers -include /nidium/Nidium/third-party/.default/mozilla-central/config/gcc_hidden.h -DIMPL_MFBT -I/nidium/Nidium/third-party/.default/mozilla-central/mfbt -I.  -I../dist/include  -I/nidium/Nidium/third-party/.default/mozilla-central/nsprpub/dist/include/nspr/        -fPIC  -DMOZILLA_CLIENT -include ../js/src/js-confdefs.h -MD -MP -MF .deps/Compression.o.pp -Qunused-arguments  -Qunused-arguments -Wno-inline-new-delete -Wall -Wsign-compare -Wtype-limits -Wno-invalid-offsetof -Wno-c++0x-extensions -Wno-extended-offsetof -Wno-unknown-warning-option -Wno-return-type-c-linkage -fno-rtti -fno-exceptions -fno-math-errno -std=gnu++0x -pthread -pipe  -DNDEBUG -DTRIMMED -g -O3 -fomit-frame-pointer   -Wno-unused-function  /nidium/Nidium/third-party/.default/mozilla-central/mfbt/Compression.cpp
Note: rebuild with "make VERBOSE=1 " to show all compiler parameters.
Decimal.o
make[4]: Making `all' in `stubdata'
make[5]: Entering directory '/nidium/Nidium/third-party/.default/mozilla-central/js/src/obj/intl/icu/target/stubdata'
make[5]: Nothing to be done for 'all'.
make[5]: Leaving directory '/nidium/Nidium/third-party/.default/mozilla-central/js/src/obj/intl/icu/target/stubdata'
make[4]: Making `all' in `common'
In file included from /nidium/Nidium/third-party/.default/mozilla-central/mfbt/Compression.cpp:7:
In file included from ../dist/include/mozilla/Compression.h:12:
In file included from ../dist/include/mozilla/Assertions.h:43:
In file included from /nidium/Nidium/third-party/.default/mozilla-central/js/src/obj/dist/system_wrappers/stdlib.h:3:
In file included from /usr/include/stdlib.h:42:
In file included from /usr/include/x86_64-linux-gnu/bits/waitstatus.h:64:
In file included from /nidium/Nidium/third-party/.default/mozilla-central/js/src/obj/dist/system_wrappers/endian.h:3:
In file included from /nidium/Nidium/third-party/.default/mozilla-central/mfbt/endian.h:70:
../dist/include/mozilla/DebugOnly.h:36:1: error: templates must have C++ linkage
template<typename T>
^~~~~~~~~~~~~~~~~~~~
In file included from /nidium/Nidium/third-party/.default/mozilla-central/mfbt/Compression.cpp:7:
In file included from ../dist/include/mozilla/Compression.h:12:
In file included from ../dist/include/mozilla/Assertions.h:43:
In file included from /nidium/Nidium/third-party/.default/mozilla-central/js/src/obj/dist/system_wrappers/stdlib.h:3:
In file included from /usr/include/stdlib.h:42:
In file included from /usr/include/x86_64-linux-gnu/bits/waitstatus.h:64:
In file included from /nidium/Nidium/third-party/.default/mozilla-central/js/src/obj/dist/system_wrappers/endian.h:3:
In file included from /nidium/Nidium/third-party/.default/mozilla-central/mfbt/endian.h:71:
../dist/include/mozilla/TypeTraits.h:26:1: error: templates must have C++ linkage
template<typename> struct RemoveCV;
^~~~~~~~~~~~~~~~~~
../dist/include/mozilla/TypeTraits.h:27:1: error: templates must have C++ linkage
template<typename> struct AddRvalueReference;
^~~~~~~~~~~~~~~~~~
../dist/include/mozilla/TypeTraits.h:38:10: error: expected a qualified name after 'typename'
typename AddRvalueReference<T>::Type DeclVal();
         ^
../dist/include/mozilla/TypeTraits.h:37:1: error: templates must have C++ linkage
template<typename T>
^~~~~~~~~~~~~~~~~~~~
../dist/include/mozilla/TypeTraits.h:38:28: error: expected ';' at end of declaration
typename AddRvalueReference<T>::Type DeclVal();
                           ^
../dist/include/mozilla/TypeTraits.h:38:28: error: expected unqualified-id
../dist/include/mozilla/TypeTraits.h:46:1: error: templates must have C++ linkage
template<typename T, T Value>
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../dist/include/mozilla/TypeTraits.h:55:9: error: unknown type name 'IntegralConstant'
typedef IntegralConstant<bool, true> TrueType;
        ^
../dist/include/mozilla/TypeTraits.h:55:25: error: expected unqualified-id
typedef IntegralConstant<bool, true> TrueType;
                        ^
../dist/include/mozilla/TypeTraits.h:56:9: error: unknown type name 'IntegralConstant'
typedef IntegralConstant<bool, false> FalseType;
        ^
../dist/include/mozilla/TypeTraits.h:56:25: error: expected unqualified-id
typedef IntegralConstant<bool, false> FalseType;
                        ^
../dist/include/mozilla/TypeTraits.h:64:1: error: templates must have C++ linkage
template<typename T>
^~~~~~~~~~~~~~~~~~~~
../dist/include/mozilla/TypeTraits.h:65:23: error: expected class name
struct IsVoidHelper : FalseType {};
                      ^
../dist/include/mozilla/TypeTraits.h:68:8: error: explicit specialization of non-template struct 'IsVoidHelper'
struct IsVoidHelper<void> : TrueType {};
       ^           ~~~~~~
../dist/include/mozilla/TypeTraits.h:68:29: error: expected class name
struct IsVoidHelper<void> : TrueType {};
                            ^
../dist/include/mozilla/TypeTraits.h:80:1: error: templates must have C++ linkage
template<typename T>
^~~~~~~~~~~~~~~~~~~~
../dist/include/mozilla/TypeTraits.h:81:25: error: unknown template name 'IsVoidHelper'
struct IsVoid : detail::IsVoidHelper<typename RemoveCV<T>::Type> {};
                        ^
../dist/include/mozilla/TypeTraits.h:81:47: error: expected a qualified name after 'typename'
struct IsVoid : detail::IsVoidHelper<typename RemoveCV<T>::Type> {};
                                              ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
/nidium/Nidium/third-party/.default/mozilla-central/config/rules.mk:956: recipe for target 'Compression.o' failed
make[3]: *** [Compression.o] Error 1
make[3]: Leaving directory '/nidium/Nidium/third-party/.default/mozilla-central/js/src/obj/mfbt'
/nidium/Nidium/third-party/.default/mozilla-central/config/recurse.mk:71: recipe for target 'mfbt/target' failed
make[2]: *** [mfbt/target] Error 2
make[2]: *** Waiting for unfinished jobs....
```

the system I used

```bash
root@b9db9671b284:/nidium/Nidium# cat /proc/version
Linux version 4.4.27-moby (root@1d811a9194c4) (gcc version 5.3.0 (Alpine 5.3.0) ) #1 SMP Wed Oct 26 14:21:29 UTC 2016
root@b9db9671b284:/nidium/Nidium# cat /etc/issue
Debian GNU/Linux 8 \n \l

root@b9db9671b284:/nidium/Nidium# cat /etc/debian_version
8.6
root@b9db9671b284:/nidium/Nidium#
```

**Comment by verpeteren** [comment]
What compiler version are you using? (`clang++ --version`)
Nidium should compile fine with clang 3.7.

**Comment by sovanna** [comment]
a you're right, ma clang shipped with jessie is not up to date

```bash
root@b9db9671b284:/nidium# clang++ --version
Debian clang version 3.5.0-10 (tags/RELEASE_350/final) (based on LLVM 3.5.0)
Target: x86_64-pc-linux-gnu
Thread model: posix
```

try to update it tonight, keep in touch

**Comment by verpeteren** [comment]
* for Debian 8, currently only 3.4 and 3.5 are in the repositories.
* for building clang from scratch there are some caveats to get lldb and asan working. I have a script laying around somewhere that makes it easy as pie; contact me if you want to persue this route.
* for clang > 3.7 there are nice [pre build binaries for Clang x86_84](http://llvm.org/releases/download.html#3.7.1). While you are on debian, you'd probably need to do something like:

```
cd /opt && \
wget -q http://llvm.org/releases/3.7.1/clang+llvm-3.7.1-x86_64-linux-gnu-debian8.tar.xz && \
tar -xaf clang+llvm-3.7.1-x86_64-linux-gnu-debian8.tar.xz && \
update-alternatives --install /usr/bin/clang  clang /opt/clang+llvm-3.7.1-x86_64-linux-gnu-debian8/bin/clang 37
update-alternatives --install /usr/bin/clang++  clang++ /opt/clang+llvm-3.7.1-x86_64-linux-gnu-debian8/bin/clang++ 37 && \
update-alternatives --config clang && \
update-alternatives --config clang++
# You might want to put these in some script or  '~/.bashrc'
export ASAN_OPTIONS=symbolize=1
export ASAN_SYMBOLIZER_PATH=/opt/clang+llvm-3.7.1-x86_64-linux-gnu-debian8/bin/llvm-symbolizer
```

I'll close this issue now, feel free to reopen.

**Comment by paraboul** [comment]
Well I doubt that Spidermonkey doesnt build en 3.5. This night be another issue

**Comment by efyx** [comment]
I am closing this issue for now as we are not able to reproduce this issue (nidium builds fine with clang-3.5 on debian jessie)
